package exception;

import java.util.Scanner;

public class ExceptionTest03 {
	public static void main(String[] args) {
		Scanner key = new Scanner(System.in);
		/*try {
			
		}catch(Exception e) {
			
		}*/
		int i = 10;
		while(i<=13) {
			System.out.println("나누기할 숫자:");
			int num = key.nextInt();
			try {
				System.out.println("값:"+i/num);
			}catch(ArithmeticException e) {
				System.out.println("0으로 나누면 error!!");
			}
		}
	} 
}
